# Generated by Django 4.0.2 on 2022-02-20 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='post',
            name='source',
        ),
    ]
