# Generated by Django 4.0.2 on 2022-03-25 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_delete_postimage_alter_post_imgcontent'),
        ('posts', '0009_alter_post_img_content'),
    ]

    operations = [
    ]
