# Generated by Django 4.0.2 on 2022-04-04 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_remotecomment'),
        ('posts', '0015_alter_post_shared_author_delete_sharedpost'),
    ]

    operations = [
    ]
