# Generated by Django 4.0.2 on 2022-04-04 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0005_remotefollow'),
        ('follow', '0005_remoterequest_remotefollower'),
    ]

    operations = [
    ]
