# Generated by Django 4.0.2 on 2022-04-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0006_rename_remoterquest_remoterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoterequest',
            name='from_user_name',
            field=models.CharField(default='', max_length=512),
        ),
    ]
