name: CI

env:
  AWS_STORAGE_BUCKET_NAME: 'cmput404-test'
  AWS_ACCESS_KEY_ID: 'AKIA4HM362I6GGM65U6F'
  AWS_SECRET_ACCESS_KEY: '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'  

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Format test
        run: |
          autopep8 --diff -r . --exclude="*/.git/*,*/venv/*,*/__pycache__/*,*/migrations/*" --exit-code
      - name: Run Tests
        run: |
          python manage.py test
